### ISSUE TITLE
Deploy fails on yq v4.x

### ISSUE THREAD

**Issue by ankumar** [gneisstech/bedrock#27]
./recipes/deploy_environment_cluster.sh BR_Development
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.

**Comment by ankumar** [comment]
@PaulCharlton https://mikefarah.gitbook.io/yq/

**Comment by cvraocv** [comment]
With yq 2, it throws parsing error ... parse error: Invalid numeric literal at line 1, column 6

**Comment by ankumar** [comment]
workaround:

wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && chmod +x /usr/bin/yq

For instance Mac, VERSION=3.4.1 and BINARY=yq_darwin_amd64

wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_darwin_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq

**Comment by PaulCharlton** [comment]
fixed in two ways:  (1) containerization of bedrock core commands avoids local developer's tool versions, and (2) upgraded bedrock container to use YQ 4.x
